apiVersion: v1
kind: Pod
metadata:
  name: meupod1
  labels:
  name: test1
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: meupod2
  labels:
  name: test1
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
